apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-ingress-demo
spec:
  type: ClusterIP
  selector:
    app: nginx-ingress-demo-rs
  ports:
    - name: http
      port: 80
      targetPort: 80
