apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx-demo-rs-labels ## this has not importance at this point.
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo-pod-labels ## this is the label we will use to match the pods
  template:
    metadata:
      labels:
        app: nginx-demo-pod-labels ## this is the label we will use to match the pods
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
